services:

  api:
    image: one.zuman.api:$FLASK_ENV
    restart: always
    ports:
      - "$PORT:8000"
    volumes:
      - ./db/migrations:/app/migrations
      - ./db/profile_pics:/app/zuman/static/profile_pics
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - common-proxy_default
      - zuman-network

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db/data:/var/zuman.one/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/zuman.one/data/pgdata
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - zuman-network

networks:
  common-proxy_default:
    external: true
  zuman-network:
    external: false
