services:

  zuman-api:
    build: api
    volumes:
      - ./db/migrations:/app/migrations
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - proxy-network
      - zuman-network

  db:
    image: postgres:alpine
    ports:
      - "2345:5432"
    volumes:
      - ./db/data:/var/zuman.one/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/zuman.one/data/pgdata
      - POSTGRES_PASSWORD=
    networks:
      - zuman-network

networks:
  proxy-network:
    external: true
  zuman-network:
    external: false
