version: '3.9'
services:
  web:
    build: web
    ports:
      - "5000:5000"
    volumes:
      - ./web/config:/var/zuman.one
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    links:
      - memcached
  memcached:
    image: memcached
