version: '3.9'
services:

  web:
    build: web
    ports:
      - "5000:5000"
    volumes:
      - ./db/migrations:/app/migrations
    env_file:
      - .env
    depends_on:
      - memcached
      - db

  memcached:
    image: memcached

  db:
    image: postgres:alpine
    ports:
      - "2345:5432"
    volumes:
      - ./db/data:/var/zuman.one/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/zuman.one/data/pgdata
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
